Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.hostname = "ovpnclient"
  
  config.vm.provider :libvirt do |libvirt|
    libvirt.username='root'
    libvirt.password='vagrant'
  end 
  
  config.vm.provision "file", source: "./keys", destination: "/tmp/keys" 
  config.vm.provision "file", source: "./client.ovpn", destination: "/tmp/client.ovpn"
  
  config.vm.provision "shell", privileged: true, inline: <<-SHELL 
    wget https://github.com/microsoft/PQCrypto-VPN/releases/download/PQCrypto-1.1/pq-openvpn-linux-staged.tar.gz -O /pq-openvpn-linux-staged.tar.gz  
    cd /
    tar -xvzf /pq-openvpn-linux-staged.tar.gz 
    cp -rf /tmp/keys /usr/local/openvpn/etc/
    cp /tmp/client.ovpn /usr/local/openvpn/etc/
  SHELL
end
